[workspace]
resolver = "2"
members = [
    "stutter",
    "stutter-common",
    "stutter-config",
    "stutter-core",
    "stutter-ebpf",
    "stutter-report",
    "xtask",
]
default-members = ["stutter", "stutter-common", "stutter-config", "stutter-core", "stutter-report"]

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2024"

[workspace.dependencies]
aya = { git = "https://github.com/aya-rs/aya", default-features = false }
aya-build = { git = "https://github.com/aya-rs/aya", default-features = false }
aya-ebpf = { git = "https://github.com/aya-rs/aya", default-features = false }
aya-log = { git = "https://github.com/aya-rs/aya", default-features = false }
aya-log-ebpf = { git = "https://github.com/aya-rs/aya", default-features = false }

anyhow = { version = "1", default-features = false }
axum = "0.7"
cargo_metadata = { version = "0.23.0", default-features = false }
# `std` feature is currently required to build `clap`.
#
# See https://github.com/clap-rs/clap/blob/61f5ee5/clap_builder/src/lib.rs#L15.
clap = { version = "4.5.20", default-features = false, features = ["std", "derive"] }
clap_complete = "4"
clap_mangen = "0.2"
crossterm = "0.29.0"
env_logger = { version = "0.11.5", default-features = false }
futures-util = "0.3.32"
hyper = "1"
hyper-util = "0.1"
inferno = "0.12"
libc = { version = "0.2.159", default-features = false }
log = { version = "0.4.22", default-features = false }
opentelemetry = "0.24"
opentelemetry_sdk = { version = "0.24", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.17", features = ["grpc-tonic"] }
ratatui = "0.30.0"
reqwest = { version = "0.12", default-features = false }
serde = { version = "1", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
tempfile = "3"
thiserror = { version = "2", default-features = false }
tokio = { version = "1.40.0", default-features = false }
toml = { version = "0.8", default-features = true }
tower = "0.5"
url = "2"
wayland-client = "0.31.14"
wayland-protocols = "0.32.12"
which = { version = "6.0.0", default-features = false }
regex = "1"

[profile.release.package.stutter-ebpf]
debug = 2
codegen-units = 1
strip = false
