//! Metadata for sanitized-real validation matrix fixtures.

use super::*;

pub(super) fn fixture_metadata_for_real_matrix(
    name: &str,
    artifacts: &FixtureArtifacts,
) -> Option<FixtureMetadata> {
    Some(match name {
        "real_amd_hyprland_clean" => real_case(RealCaseInput {
            name,
            gpu_vendor: "AMD",
            gpu_driver: "amdgpu",
            compositor: "Hyprland",
            session_type: "wayland",
            scenario: "clean",
            sanitized_capture_id: "sanitized-amd-hyprland-clean-v1",
            description: "Sanitized AMD/Hyprland clean recording with normal frames and no scheduler spike diagnosis.",
            primary_cause: "Unknown",
            accepted_confidence: &[],
            data_quality: "High",
            evidence_contains: &[],
            artifacts,
        }),
        "real_nvidia_gnome_false_positive" => with_expected_behavior(
            real_case(RealCaseInput {
                name,
                gpu_vendor: "NVIDIA",
                gpu_driver: "nvidia",
                compositor: "GNOME",
                session_type: "wayland",
                scenario: "false-positive",
                sanitized_capture_id: "sanitized-nvidia-gnome-false-positive-v1",
                description: "Sanitized NVIDIA/GNOME recording with harmless GPU/frame noise that must not become a strong diagnosis.",
                primary_cause: "Unknown",
                accepted_confidence: &[],
                data_quality: "High",
                evidence_contains: &[],
                artifacts,
            }),
            FixtureExpectedBehavior::MustNotDiagnose,
        ),
        "real_intel_kwin_cpu_bound" => real_case(RealCaseInput {
            name,
            gpu_vendor: "Intel",
            gpu_driver: "i915",
            compositor: "KWin",
            session_type: "wayland",
            scenario: "cpu-bound",
            sanitized_capture_id: "sanitized-intel-kwin-cpu-bound-v1",
            description: "Sanitized Intel/KWin CPU-pressure recording with CPU PSI near scheduler-latency spikes.",
            primary_cause: "CpuPressureCandidate",
            accepted_confidence: &["Medium", "High"],
            data_quality: "High",
            evidence_contains: &["high CPU PSI"],
            artifacts,
        }),
        "real_amd_gamescope_gpu_bound" => {
            let mut metadata = real_case(RealCaseInput {
                name,
                gpu_vendor: "AMD",
                gpu_driver: "amdgpu",
                compositor: "Gamescope",
                session_type: "wayland",
                scenario: "gpu-bound",
                sanitized_capture_id: "sanitized-amd-gamescope-gpu-bound-v1",
                description: "Sanitized AMD/Gamescope GPU-bound recording with high GPU busy near a visible frame spike.",
                primary_cause: "Any",
                accepted_confidence: &[],
                data_quality: "High",
                evidence_contains: &[],
                artifacts,
            });
            metadata.expected.required_candidate = Some("GpuBoundCandidate".to_owned());
            metadata.expected.required_candidate_evidence = vec!["GPU busy".to_owned()];
            metadata
        }
        "real_nvidia_kwin_irq_overlap" => real_case(RealCaseInput {
            name,
            gpu_vendor: "NVIDIA",
            gpu_driver: "nvidia",
            compositor: "KWin",
            session_type: "wayland",
            scenario: "irq",
            sanitized_capture_id: "sanitized-nvidia-kwin-irq-overlap-v1",
            description: "Sanitized NVIDIA/KWin recording with a GPU IRQ handler overlapping a scheduler-latency cluster.",
            primary_cause: "IrqDelayCandidate",
            accepted_confidence: &["Medium", "High"],
            data_quality: "High",
            evidence_contains: &["IRQ"],
            artifacts,
        }),
        "real_intel_sway_compositor_delay" => real_case(RealCaseInput {
            name,
            gpu_vendor: "Intel",
            gpu_driver: "i915",
            compositor: "Sway",
            session_type: "wayland",
            scenario: "compositor",
            sanitized_capture_id: "sanitized-intel-sway-compositor-delay-v1",
            description: "Sanitized Intel/Sway recording with compositor scheduler delay during a visible frame spike.",
            primary_cause: "CompositorSchedulerDelay",
            accepted_confidence: &["Medium", "High"],
            data_quality: "High",
            evidence_contains: &["compositor thread"],
            artifacts,
        }),
        "real_gpu_bound_looking" => {
            let mut metadata = real_case(RealCaseInput {
                name,
                gpu_vendor: "AMD",
                gpu_driver: "amdgpu",
                compositor: "Gamescope",
                session_type: "wayland",
                scenario: "gpu-bound",
                sanitized_capture_id: "sanitized-amd-gamescope-gpu-bound-looking-v1",
                description: "GPU busy was high during a visible frame spike; scheduler evidence may also exist, so GPU-bound is required as a candidate rather than always primary.",
                primary_cause: "Any",
                accepted_confidence: &[],
                data_quality: "High",
                evidence_contains: &[],
                artifacts,
            });
            metadata.expected.required_candidate = Some("GpuBoundCandidate".to_owned());
            metadata.expected.required_candidate_evidence = vec!["GPU busy".to_owned()];
            metadata
        }
        "real_block_io_overlap" => real_case(RealCaseInput {
            name,
            gpu_vendor: "NVIDIA",
            gpu_driver: "nvidia",
            compositor: "KWin",
            session_type: "wayland",
            scenario: "block-io",
            sanitized_capture_id: "sanitized-nvidia-kwin-block-io-overlap-v1",
            description: "Block I/O request overlapped the scheduler-latency cluster while unrelated block I/O occurred outside the correlation window.",
            primary_cause: "BlockIoCandidate",
            accepted_confidence: &["Medium", "High"],
            data_quality: "High",
            evidence_contains: &["block I/O"],
            artifacts,
        }),
        "real_truncated_low_quality" => with_quality_reasons(
            real_case(RealCaseInput {
                name,
                gpu_vendor: "Intel",
                gpu_driver: "i915",
                compositor: "Sway",
                session_type: "wayland",
                scenario: "low-quality",
                sanitized_capture_id: "sanitized-intel-sway-truncated-low-quality-v1",
                description: "Sanitized low-quality recording with truncated spike events and nonzero drop counters; quality handling is the regression target, not diagnosis cause detection.",
                primary_cause: "Unknown",
                accepted_confidence: &[],
                data_quality: "Medium",
                evidence_contains: &[],
                artifacts,
            }),
            &["truncated", "drop"],
        ),
        "real_foreground_window" => real_case(RealCaseInput {
            name,
            gpu_vendor: "AMD",
            gpu_driver: "amdgpu",
            compositor: "Sway",
            session_type: "wayland",
            scenario: "foreground",
            sanitized_capture_id: "sanitized-amd-sway-foreground-window-v1",
            description: "Sanitized foreground-window recording with a scheduler cluster near a foreground event; title is redacted while PID/app/class remain available.",
            primary_cause: "Any",
            accepted_confidence: &[],
            data_quality: "High",
            evidence_contains: &[],
            artifacts,
        }),
        "real_community_rules_classification" => real_case(RealCaseInput {
            name,
            gpu_vendor: "NVIDIA",
            gpu_driver: "nvidia",
            compositor: "GNOME",
            session_type: "wayland",
            scenario: "community",
            sanitized_capture_id: "sanitized-nvidia-gnome-community-rules-v1",
            description: "Sanitized community-rules classification fixture where an originally unknown game process is represented in the final artifact stream as TaskClass::Game.",
            primary_cause: "GameThreadSchedulerDelay",
            accepted_confidence: &["Medium", "High"],
            data_quality: "High",
            evidence_contains: &["game thread", "delayed"],
            artifacts,
        }),
        "real_clean_baseline" => real_case(RealCaseInput {
            name,
            gpu_vendor: "AMD",
            gpu_driver: "amdgpu",
            compositor: "Hyprland",
            session_type: "wayland",
            scenario: "clean",
            sanitized_capture_id: "sanitized-amd-hyprland-clean-baseline-v1",
            description: "Real clean baseline example.",
            primary_cause: "Unknown",
            accepted_confidence: &[],
            data_quality: "High",
            evidence_contains: &[],
            artifacts,
        }),
        "real_intel_gnome_frame_jitter_false_positive" => with_expected_behavior(
            real_case(RealCaseInput {
                name,
                gpu_vendor: "Intel",
                gpu_driver: "i915",
                compositor: "GNOME",
                session_type: "wayland",
                scenario: "false-positive",
                sanitized_capture_id: "sanitized-intel-gnome-frame-jitter-fp-v1",
                description: "Sanitized Intel/GNOME recording with benign frame jitter that must not become a strong diagnosis.",
                primary_cause: "Unknown",
                accepted_confidence: &[],
                data_quality: "High",
                evidence_contains: &[],
                artifacts,
            }),
            FixtureExpectedBehavior::MustNotDiagnose,
        ),
        "real_amd_kwin_overlay_false_positive" => with_expected_behavior(
            real_case(RealCaseInput {
                name,
                gpu_vendor: "AMD",
                gpu_driver: "amdgpu",
                compositor: "KWin",
                session_type: "wayland",
                scenario: "false-positive",
                sanitized_capture_id: "sanitized-amd-kwin-overlay-fp-v1",
                description: "Sanitized AMD/KWin direct-scanout recording with harmless overlay/display-path noise that must not become a strong diagnosis.",
                primary_cause: "Unknown",
                accepted_confidence: &[],
                data_quality: "High",
                evidence_contains: &[],
                artifacts,
            }),
            FixtureExpectedBehavior::MustNotDiagnose,
        ),
        "real_known_miss_sparse_gpu_bound" => with_expected_behavior(
            real_case(RealCaseInput {
                name,
                gpu_vendor: "AMD",
                gpu_driver: "amdgpu",
                compositor: "Gamescope",
                session_type: "wayland",
                scenario: "known-miss",
                sanitized_capture_id: "sanitized-amd-gamescope-known-miss-gpu-v1",
                description: "Known false-negative catalogue entry for a sparse GPU-bound capture shape that current heuristics intentionally do not diagnose yet.",
                primary_cause: "GpuBoundCandidate",
                accepted_confidence: &[],
                data_quality: "High",
                evidence_contains: &[],
                artifacts,
            }),
            FixtureExpectedBehavior::KnownMiss,
        ),
        "real_known_miss_short_irq_overlap" => with_expected_behavior(
            real_case(RealCaseInput {
                name,
                gpu_vendor: "NVIDIA",
                gpu_driver: "nvidia",
                compositor: "KWin",
                session_type: "wayland",
                scenario: "known-miss",
                sanitized_capture_id: "sanitized-nvidia-kwin-known-miss-irq-v1",
                description: "Known false-negative catalogue entry for a short IRQ-overlap capture shape that current heuristics intentionally do not diagnose yet.",
                primary_cause: "IrqDelayCandidate",
                accepted_confidence: &[],
                data_quality: "High",
                evidence_contains: &[],
                artifacts,
            }),
            FixtureExpectedBehavior::KnownMiss,
        ),
        "real_known_miss_block_io_tail" => with_expected_behavior(
            real_case(RealCaseInput {
                name,
                gpu_vendor: "Intel",
                gpu_driver: "i915",
                compositor: "Sway",
                session_type: "wayland",
                scenario: "known-miss",
                sanitized_capture_id: "sanitized-intel-sway-known-miss-block-io-v1",
                description: "Known false-negative catalogue entry for a late block-I/O tail capture shape that current heuristics intentionally do not diagnose yet.",
                primary_cause: "BlockIoCandidate",
                accepted_confidence: &[],
                data_quality: "High",
                evidence_contains: &[],
                artifacts,
            }),
            FixtureExpectedBehavior::KnownMiss,
        ),
        "real_compositor_scheduler_delay" => real_case(RealCaseInput {
            name,
            gpu_vendor: "Intel",
            gpu_driver: "i915",
            compositor: "Sway",
            session_type: "wayland",
            scenario: "compositor",
            sanitized_capture_id: "sanitized-intel-sway-compositor-scheduler-v1",
            description: "Compositor or gamescope thread had scheduler delay during a visible frame spike.",
            primary_cause: "CompositorSchedulerDelay",
            accepted_confidence: &["Medium", "High"],
            data_quality: "High",
            evidence_contains: &["compositor thread"],
            artifacts,
        }),
        "real_game_thread_scheduler_delay" => real_case(RealCaseInput {
            name,
            gpu_vendor: "NVIDIA",
            gpu_driver: "nvidia",
            compositor: "KWin",
            session_type: "wayland",
            scenario: "game",
            sanitized_capture_id: "sanitized-nvidia-kwin-game-thread-scheduler-v1",
            description: "Real game-thread scheduler delay example.",
            primary_cause: "GameThreadSchedulerDelay",
            accepted_confidence: &["Medium", "High"],
            data_quality: "High",
            evidence_contains: &["game thread", "delayed"],
            artifacts,
        }),
        "real_irq_overlap" => real_case(RealCaseInput {
            name,
            gpu_vendor: "NVIDIA",
            gpu_driver: "nvidia",
            compositor: "KWin",
            session_type: "wayland",
            scenario: "irq",
            sanitized_capture_id: "sanitized-nvidia-kwin-irq-overlap-legacy-v1",
            description: "IRQ handler activity overlapped the scheduler-latency cluster while unrelated IRQ noise occurred outside the correlation window.",
            primary_cause: "IrqDelayCandidate",
            accepted_confidence: &["Medium", "High"],
            data_quality: "High",
            evidence_contains: &["IRQ"],
            artifacts,
        }),
        _ => return None,
    })
}

struct RealCaseInput<'a> {
    name: &'a str,
    gpu_vendor: &'a str,
    gpu_driver: &'a str,
    compositor: &'a str,
    session_type: &'a str,
    scenario: &'a str,
    sanitized_capture_id: &'a str,
    description: &'a str,
    primary_cause: &'a str,
    accepted_confidence: &'a [&'a str],
    data_quality: &'a str,
    evidence_contains: &'a [&'a str],
    artifacts: &'a FixtureArtifacts,
}

fn real_case(input: RealCaseInput<'_>) -> FixtureMetadata {
    with_platform(
        fixture_metadata(FixtureMetadataInput {
            name: input.name,
            source: "sanitized-real-recording",
            quality_expectation: input.data_quality,
            description: input.description,
            primary_cause: input.primary_cause,
            accepted_confidence: input.accepted_confidence,
            data_quality: input.data_quality,
            evidence_contains: input.evidence_contains,
            artifacts: exact_artifacts(input.artifacts),
        }),
        real_platform(
            input.gpu_vendor,
            input.gpu_driver,
            input.compositor,
            input.session_type,
            input.scenario,
            input.sanitized_capture_id,
        ),
    )
}
