use std::{fs, path::PathBuf};

use anyhow::Context;

use crate::{
    affinity::CpuMask,
    autotune::candidate::{GeneratedCpuSetPolicy, generate_topology_aware_profiles_with_policy},
    profiles::{Profile, render_profiles_toml},
    topology::TopologyModel,
};

#[derive(Debug, Clone)]
pub struct GenerateProfilesCommandInput {
    pub watch_process: Option<String>,
    pub out: PathBuf,
    pub allow_cpus: Option<String>,
    pub deny_cpus: Option<String>,
    pub min_render_cpus: usize,
    pub min_game_cpus: usize,
    pub min_compositor_cpus: usize,
    pub min_background_cpus: usize,
}

pub fn generate_profiles_command(input: GenerateProfilesCommandInput) -> anyhow::Result<()> {
    let topology = TopologyModel::read().context("failed to read CPU topology")?;
    generate_profiles_command_with_topology(input, &topology)
}

pub fn generate_profiles_command_with_topology(
    input: GenerateProfilesCommandInput,
    topology: &TopologyModel,
) -> anyhow::Result<()> {
    let policy = GeneratedCpuSetPolicy {
        allowed_cpus: parse_optional_cpu_mask(input.allow_cpus.as_deref(), "--allow-cpus")?,
        denied_cpus: parse_optional_cpu_mask(input.deny_cpus.as_deref(), "--deny-cpus")?,
        min_render_cpus: input.min_render_cpus,
        min_game_cpus: input.min_game_cpus,
        min_compositor_cpus: input.min_compositor_cpus,
        min_background_cpus: input.min_background_cpus,
    };

    let plan = generate_topology_aware_profiles_with_policy(topology, &policy);

    if plan.profiles.is_empty() {
        let rejected = plan
            .rejected
            .iter()
            .map(|rejected| format!("{}: {}", rejected.profile_name, rejected.reason))
            .collect::<Vec<_>>()
            .join("; ");
        anyhow::bail!(
            "no generated profiles passed validation; rejected=[{}]",
            rejected
        );
    }

    let output = render_generated_profiles_toml(input.watch_process.as_deref(), &plan.profiles);

    if input.out.as_os_str() == "-" {
        print!("{output}");
    } else {
        if let Some(parent) = input.out.parent()
            && !parent.as_os_str().is_empty()
        {
            fs::create_dir_all(parent).with_context(|| {
                format!("failed to create output directory {}", parent.display())
            })?;
        }

        fs::write(&input.out, output).with_context(|| {
            format!(
                "failed to write generated profiles to {}",
                input.out.display()
            )
        })?;
        println!(
            "generated {} profile(s) at {}",
            plan.profiles.len(),
            input.out.display()
        );
    }

    for rejected in &plan.rejected {
        eprintln!(
            "rejected generated profile {}: {}",
            rejected.profile_name, rejected.reason
        );
    }

    Ok(())
}

fn render_generated_profiles_toml(watch_process: Option<&str>, profiles: &[Profile]) -> String {
    let mut output = String::new();
    output.push_str("# Generated by stutter autotune generate-profiles.\n");
    output.push_str(
        "# Review before applying with: stutter apply-profile --tree-pid <PID> --profile <FILE>\n",
    );

    if let Some(watch_process) = watch_process {
        output.push_str("# Intended watch process: ");
        output.push_str(&comment_safe_value(watch_process));
        output.push('\n');
    }

    output.push('\n');
    output.push_str(&render_profiles_toml(profiles));
    output
}

fn comment_safe_value(value: &str) -> String {
    value
        .chars()
        .map(|ch| match ch {
            '\n' | '\r' => ' ',
            other => other,
        })
        .collect()
}

fn parse_optional_cpu_mask(
    value: Option<&str>,
    flag_name: &str,
) -> anyhow::Result<Option<CpuMask>> {
    match value {
        Some(value) => CpuMask::parse(value)
            .map(Some)
            .with_context(|| format!("failed to parse {flag_name} value {value:?}")),
        None => Ok(None),
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::*;
    use crate::{
        affinity::CpuMask,
        topology::{CoreInfo, CpuInfo, TopologyModel},
    };

    #[test]
    fn render_generated_profiles_toml_includes_header_and_profiles() {
        let topology = fake_topology_4c8t();
        let plan = generate_topology_aware_profiles_with_policy(
            &topology,
            &GeneratedCpuSetPolicy::default(),
        );

        let text = render_generated_profiles_toml(Some("Game.exe"), &plan.profiles);

        assert!(text.contains("# Generated by stutter autotune generate-profiles."));
        assert!(text.contains("# Intended watch process: Game.exe"));
        assert!(text.contains("name = \"baseline-online\""));
        assert!(text.contains("name = \"game-isolate-render\""));
        assert!(text.contains("name = \"avoid-smt-contention\""));
    }

    #[test]
    fn generate_profiles_command_writes_output_file() {
        let topology = fake_topology_4c8t();
        let out = temp_output_path("generated-profiles.toml");

        generate_profiles_command_with_topology(
            GenerateProfilesCommandInput {
                watch_process: Some("Game.exe".to_owned()),
                out: out.clone(),
                allow_cpus: None,
                deny_cpus: None,
                min_render_cpus: 1,
                min_game_cpus: 1,
                min_compositor_cpus: 1,
                min_background_cpus: 2,
            },
            &topology,
        )
        .unwrap();

        let text = fs::read_to_string(&out).unwrap();
        assert!(text.contains("# Intended watch process: Game.exe"));
        assert!(text.contains("[[profile]]"));
        assert!(text.contains("name = \"baseline-online\""));
        assert!(text.contains("name = \"game-isolate-render\""));

        fs::remove_file(out).ok();
    }

    #[test]
    fn generate_profiles_command_rejects_invalid_allow_set() {
        let topology = fake_topology_4c8t();
        let out = temp_output_path("generated-profiles-invalid.toml");

        let err = generate_profiles_command_with_topology(
            GenerateProfilesCommandInput {
                watch_process: Some("Game.exe".to_owned()),
                out,
                allow_cpus: Some("not-a-cpu".to_owned()),
                deny_cpus: None,
                min_render_cpus: 1,
                min_game_cpus: 1,
                min_compositor_cpus: 1,
                min_background_cpus: 2,
            },
            &topology,
        )
        .unwrap_err();

        assert!(err.to_string().contains("failed to parse --allow-cpus"));
    }

    #[test]
    fn generate_profiles_command_bails_when_all_profiles_rejected() {
        let topology = fake_topology_4c8t();
        let out = temp_output_path("generated-profiles-rejected.toml");

        let err = generate_profiles_command_with_topology(
            GenerateProfilesCommandInput {
                watch_process: Some("Game.exe".to_owned()),
                out,
                allow_cpus: Some("0".to_owned()),
                deny_cpus: Some("0".to_owned()),
                min_render_cpus: 1,
                min_game_cpus: 1,
                min_compositor_cpus: 1,
                min_background_cpus: 2,
            },
            &topology,
        )
        .unwrap_err();

        assert!(
            err.to_string()
                .contains("no generated profiles passed validation")
        );
    }

    fn fake_topology_4c8t() -> TopologyModel {
        TopologyModel {
            online_cpus: CpuMask::parse("0-7").unwrap(),
            cpus: vec![
                fake_cpu(0, 0, 0, 0, 5000),
                fake_cpu(1, 1, 0, 0, 4900),
                fake_cpu(2, 2, 0, 0, 4800),
                fake_cpu(3, 3, 0, 0, 4700),
                fake_cpu(4, 0, 0, 0, 5000),
                fake_cpu(5, 1, 0, 0, 4900),
                fake_cpu(6, 2, 0, 0, 4800),
                fake_cpu(7, 3, 0, 0, 4700),
            ],
            cores: vec![
                fake_core(0, 0, 0, vec![0, 4], 5000),
                fake_core(1, 0, 0, vec![1, 5], 4900),
                fake_core(2, 0, 0, vec![2, 6], 4800),
                fake_core(3, 0, 0, vec![3, 7], 4700),
            ],
            smt_siblings: BTreeMap::from([
                (0, vec![0, 4]),
                (4, vec![0, 4]),
                (1, vec![1, 5]),
                (5, vec![1, 5]),
                (2, vec![2, 6]),
                (6, vec![2, 6]),
                (3, vec![3, 7]),
                (7, vec![3, 7]),
            ]),
            numa_nodes: BTreeMap::from([(0, vec![0, 1, 2, 3, 4, 5, 6, 7])]),
            packages: BTreeMap::from([(0, vec![0, 1, 2, 3, 4, 5, 6, 7])]),
        }
    }

    fn fake_cpu(cpu: u32, core_id: u32, package_id: u32, numa_node: u32, max_mhz: u64) -> CpuInfo {
        CpuInfo {
            cpu,
            core_id: Some(core_id),
            package_id: Some(package_id),
            numa_node: Some(numa_node),
            max_mhz: Some(max_mhz),
            is_online: true,
        }
    }

    fn fake_core(
        core_id: u32,
        package_id: u32,
        numa_node: u32,
        cpus: Vec<u32>,
        max_mhz: u64,
    ) -> CoreInfo {
        CoreInfo {
            core_id: Some(core_id),
            package_id: Some(package_id),
            numa_node: Some(numa_node),
            cpus,
            max_mhz: Some(max_mhz),
            is_online: true,
        }
    }

    fn temp_output_path(name: &str) -> PathBuf {
        let mut path = std::env::temp_dir();
        path.push(format!(
            "stutter-{name}-{}-{}",
            std::process::id(),
            crate::audit::unix_nanos_now()
        ));
        path
    }
}
