use std::{path::PathBuf, time::Duration};

use crate::{
    config_model::MonitorConfig,
    types::{CsvStreamTarget, FocusSource, ForegroundSource, WaylandPresentationSource},
};

#[derive(Debug, Clone, Default, PartialEq)]
pub struct MonitorConfigLayer {
    pub target_pids: Option<Vec<u32>>,
    pub tree_pids: Option<Vec<u32>>,
    pub cgroupv2: Option<Option<PathBuf>>,
    pub exclude_tree_pids: Option<Vec<u32>>,
    pub include_comm: Option<Vec<String>>,
    pub exclude_comm: Option<Vec<String>>,
    pub watch_process: Option<Option<String>>,
    pub persistent: Option<bool>,
    pub keep_missing_pid: Option<bool>,
    pub max_tasks: Option<usize>,

    pub summary_period_ms: Option<u64>,
    pub epoch_period_ms: Option<Option<u64>>,
    pub max_duration: Option<Option<Duration>>,
    pub spike_threshold_ns: Option<u64>,
    pub live_diagnosis_cluster_window_ms: Option<u64>,

    pub irq_latency: Option<bool>,
    pub irqs: Option<Vec<u32>>,
    pub hwmon: Option<bool>,
    pub cpu_freq: Option<bool>,
    pub faults: Option<bool>,
    pub cpu_perf: Option<bool>,
    pub block_io: Option<bool>,
    pub stat_wait: Option<bool>,
    pub runtime_slices: Option<bool>,
    pub kms_timing: Option<bool>,
    pub drm_fence_latency: Option<bool>,
    pub wayland_presentation: Option<bool>,
    pub dmabuf_tracking: Option<bool>,
    pub gpu_engine_sampling: Option<bool>,
    pub display_topology: Option<bool>,

    pub run_name: Option<Option<String>>,
    pub output_dir: Option<Option<PathBuf>>,
    pub retain_intervals: Option<Option<usize>>,
    pub retention_max_run_count: Option<Option<usize>>,
    pub retention_max_total_bytes: Option<Option<u64>>,
    pub retention_max_age_seconds: Option<Option<u64>>,
    pub retention_min_free_bytes: Option<Option<u64>>,

    pub json_stream: Option<bool>,
    pub metrics_port: Option<Option<u16>>,
    pub otlp_endpoint: Option<Option<String>>,
    pub otel_service_name: Option<String>,

    pub auto_focus: Option<bool>,
    pub focus_source: Option<FocusSource>,
    pub foreground_window: Option<bool>,
    pub foreground_source: Option<ForegroundSource>,
    pub foreground_poll_ms: Option<u64>,
    pub foreground_max_stale_ms: Option<u64>,
    pub foreground_include_title: Option<bool>,
    pub auto_focus_poll_ms: Option<u64>,
    pub auto_focus_min_confidence: Option<f32>,
    pub auto_focus_switch_cooldown_ms: Option<u64>,
    pub auto_focus_switch_margin: Option<f32>,
    pub auto_focus_required_polls: Option<u32>,
    pub auto_focus_max_roots: Option<usize>,

    pub follow_exec: Option<bool>,
    pub native_cgroup_filter: Option<bool>,

    pub watch_poll_ms: Option<u64>,
    pub watch_timeout: Option<Option<Duration>>,

    pub alert_threshold_ns: Option<Option<u64>>,
    pub alert_webhook_url: Option<Option<String>>,
    pub alert_desktop_timeout_ms: Option<u64>,

    pub csv_stream: Option<Option<CsvStreamTarget>>,
    pub verbose: Option<bool>,

    pub hwmon_root: Option<Option<PathBuf>>,
    pub hwmon_drm_card: Option<Option<String>>,
    pub hwmon_render_node: Option<Option<PathBuf>>,

    pub mangohud_log: Option<Option<PathBuf>>,
    pub mangohud_log_live: Option<bool>,
    pub mangohud_tail_idle_sleep_ms: Option<u64>,
    pub mangohud_alignment_poll_ms: Option<u64>,

    pub tui: Option<bool>,

    pub cpu_perf_kernel: Option<bool>,
    pub cpu_perf_max_tasks: Option<usize>,
    pub cpu_perf_cache_refs: Option<bool>,

    pub runtime_slices_max_tasks: Option<usize>,
    pub kms_drm_card: Option<Option<String>>,
    pub kms_connector: Option<Option<String>>,
    pub kms_crtc: Option<Option<u32>>,
    pub drm_fence_render_card: Option<Option<String>>,
    pub drm_fence_display_card: Option<Option<String>>,
    pub drm_fence_driver_filter: Option<Option<String>>,
    pub wayland_presentation_log: Option<Option<PathBuf>>,
    pub wayland_presentation_source: Option<WaylandPresentationSource>,
    pub dmabuf_log: Option<Option<PathBuf>>,
    pub display_path_label: Option<Option<String>>,
    pub display_render_gpu: Option<Option<String>>,
    pub display_scanout_gpu: Option<Option<String>>,
    pub display_connector: Option<Option<String>>,

    pub ringbuf_size_kb: Option<Option<u32>>,
    pub wakeup_map_factor: Option<Option<u32>>,
    pub target_pids_entries: Option<Option<u32>>,
    pub target_cgroup_ids_entries: Option<Option<u32>>,
    pub target_irqs_entries: Option<Option<u32>>,
    pub runnable_task_cpu_factor: Option<Option<u32>>,
    pub prev_faults_factor: Option<Option<u32>>,
    pub irq_start_entries: Option<Option<u32>>,
    pub block_start_entries: Option<Option<u32>>,
    pub kms_flip_start_entries: Option<Option<u32>>,
    pub drm_fence_wait_start_entries: Option<Option<u32>>,
    pub drm_fence_signal_entries: Option<Option<u32>>,

    pub remote: Option<Option<String>>,
}

impl MonitorConfigLayer {
    pub fn from_monitor_config(config: MonitorConfig) -> Self {
        Self {
            target_pids: Some(config.target.target_pids),
            tree_pids: Some(config.target.tree_pids),
            cgroupv2: Some(config.target.cgroupv2),
            exclude_tree_pids: Some(config.target.exclude_tree_pids),
            include_comm: Some(config.target.include_comm),
            exclude_comm: Some(config.target.exclude_comm),
            watch_process: Some(config.target.watch_process),
            persistent: Some(config.target.persistent),
            keep_missing_pid: Some(config.target.keep_missing_pid),
            max_tasks: Some(config.target.max_tasks),

            summary_period_ms: Some(config.timing.summary_period_ms),
            epoch_period_ms: Some(config.timing.epoch_period_ms),
            max_duration: Some(config.timing.max_duration),
            spike_threshold_ns: Some(config.timing.spike_threshold_ns),
            live_diagnosis_cluster_window_ms: Some(config.diagnosis.live_cluster_window_ms),

            irq_latency: Some(config.probes.irq_latency),
            irqs: Some(config.probes.irqs),
            hwmon: Some(config.probes.hwmon),
            cpu_freq: Some(config.probes.cpu_freq),
            faults: Some(config.probes.faults),
            cpu_perf: Some(config.probes.cpu_perf),
            block_io: Some(config.probes.block_io),
            stat_wait: Some(config.probes.stat_wait),
            runtime_slices: Some(config.probes.runtime_slices),
            kms_timing: Some(config.probes.kms_timing),
            drm_fence_latency: Some(config.probes.drm_fence_latency),
            wayland_presentation: Some(config.probes.wayland_presentation),
            dmabuf_tracking: Some(config.probes.dmabuf_tracking),
            gpu_engine_sampling: Some(config.probes.gpu_engine_sampling),
            display_topology: Some(config.probes.display_topology),

            run_name: Some(config.recording.run_name),
            output_dir: Some(config.recording.output_dir),
            retain_intervals: Some(config.recording.retain_intervals),
            retention_max_run_count: Some(config.recording.retention.max_run_count),
            retention_max_total_bytes: Some(config.recording.retention.max_total_bytes),
            retention_max_age_seconds: Some(config.recording.retention.max_age_seconds),
            retention_min_free_bytes: Some(config.recording.retention.min_free_bytes),

            json_stream: Some(config.outputs.json_stream),
            metrics_port: Some(config.outputs.metrics_port),
            otlp_endpoint: Some(config.outputs.otlp_endpoint),
            otel_service_name: Some(config.outputs.otel_service_name),

            auto_focus: Some(config.focus.auto_focus),
            focus_source: Some(config.focus.focus_source),
            foreground_window: Some(config.focus.foreground_window),
            foreground_source: Some(config.focus.foreground_source),
            foreground_poll_ms: Some(config.focus.foreground_poll_ms),
            foreground_max_stale_ms: Some(config.focus.foreground_max_stale_ms),
            foreground_include_title: Some(config.focus.foreground_include_title),
            auto_focus_poll_ms: Some(config.focus.auto_focus_poll_ms),
            auto_focus_min_confidence: Some(config.focus.auto_focus_min_confidence),
            auto_focus_switch_cooldown_ms: Some(config.focus.auto_focus_switch_cooldown_ms),
            auto_focus_switch_margin: Some(config.focus.auto_focus_switch_margin),
            auto_focus_required_polls: Some(config.focus.auto_focus_required_polls),
            auto_focus_max_roots: Some(config.focus.auto_focus_max_roots),

            follow_exec: Some(config.safety.follow_exec),
            native_cgroup_filter: Some(config.safety.native_cgroup_filter),

            watch_poll_ms: Some(config.watch.poll_ms),
            watch_timeout: Some(config.watch.timeout),

            alert_threshold_ns: Some(config.alerts.threshold_ns),
            alert_webhook_url: Some(config.alerts.webhook_url),
            alert_desktop_timeout_ms: Some(config.alerts.desktop_timeout_ms),

            csv_stream: Some(config.streams.csv),
            verbose: Some(config.streams.verbose),

            hwmon_root: Some(config.hwmon.root),
            hwmon_drm_card: Some(config.hwmon.drm_card),
            hwmon_render_node: Some(config.hwmon.render_node),

            mangohud_log: Some(config.mangohud.log),
            mangohud_log_live: Some(config.mangohud.log_live),
            mangohud_tail_idle_sleep_ms: Some(config.mangohud.tail_idle_sleep_ms),
            mangohud_alignment_poll_ms: Some(config.mangohud.alignment_poll_ms),

            tui: Some(config.ui.tui),

            cpu_perf_kernel: Some(config.cpu_perf.include_kernel),
            cpu_perf_max_tasks: Some(config.cpu_perf.max_tasks),
            cpu_perf_cache_refs: Some(config.cpu_perf.collect_cache_refs),

            runtime_slices_max_tasks: Some(config.runtime_slices.max_tasks),
            kms_drm_card: Some(config.kms_timing.drm_card),
            kms_connector: Some(config.kms_timing.connector),
            kms_crtc: Some(config.kms_timing.crtc),
            drm_fence_render_card: Some(config.drm_fence.render_card),
            drm_fence_display_card: Some(config.drm_fence.display_card),
            drm_fence_driver_filter: Some(config.drm_fence.driver_filter),
            wayland_presentation_log: Some(config.wayland_presentation.log_path),
            wayland_presentation_source: Some(config.wayland_presentation.source),
            dmabuf_log: Some(config.dmabuf.log_path),
            display_path_label: Some(config.display_path.label),
            display_render_gpu: Some(config.display_path.render_gpu),
            display_scanout_gpu: Some(config.display_path.scanout_gpu),
            display_connector: Some(config.display_path.connector),

            ringbuf_size_kb: Some(config.ebpf_sizing.ringbuf_size_kb),
            wakeup_map_factor: Some(config.ebpf_sizing.wakeup_map_factor),
            target_pids_entries: Some(config.ebpf_sizing.target_pids_entries),
            target_cgroup_ids_entries: Some(config.ebpf_sizing.target_cgroup_ids_entries),
            target_irqs_entries: Some(config.ebpf_sizing.target_irqs_entries),
            runnable_task_cpu_factor: Some(config.ebpf_sizing.runnable_task_cpu_factor),
            prev_faults_factor: Some(config.ebpf_sizing.prev_faults_factor),
            irq_start_entries: Some(config.ebpf_sizing.irq_start_entries),
            block_start_entries: Some(config.ebpf_sizing.block_start_entries),
            kms_flip_start_entries: Some(config.ebpf_sizing.kms_flip_start_entries),
            drm_fence_wait_start_entries: Some(config.ebpf_sizing.drm_fence_wait_start_entries),
            drm_fence_signal_entries: Some(config.ebpf_sizing.drm_fence_signal_entries),

            remote: Some(config.remote.endpoint),
        }
    }
}
