[package]
name = "stutter-ebpf"
version = "0.1.0"
edition.workspace = true
description = "eBPF tracepoint programs for stutter scheduler and system telemetry."
license = "MIT OR GPL-2.0-only"
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
stutter-common = { path = "../stutter-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "stutter"
path = "src/main.rs"
test = false
bench = false
